
tasks:
  - command: docker run --rm --name postgres -d -p 5432:5432 -e POSTGRES_PASSWORD=password postgres
  - command: sleep 10 && docker exec postgres psql -d postgres -U postgres -c 'CREATE DATABASE inst_api;'
  - command: yarn install
  - command: yarn start:dev
